-- Добавляем поле для хранения срочных целей (urgent task mode)
ALTER TABLE t_p86463701_eloquent_school_site.users 
ADD COLUMN IF NOT EXISTS urgent_goals JSONB DEFAULT NULL;

COMMENT ON COLUMN t_p86463701_eloquent_school_site.users.urgent_goals 
IS 'Список конкретных целей для срочных задач (generated by Gemini)';